--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent

local package = PackageIndex["roblox_rodux-presence-5fd815e4-a1b1ccc8"]["rodux-presence"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package